version: '3'
services:
####################################################################################################
# Creating container PHP
####################################################################################################
  php:
      build: ./php/
      container_name: 'php'
      ports:
          - 9000:9000
      volumes:
          - ..:/var/www

####################################################################################################
# Creating container (Nginx)
####################################################################################################
  nginx:
      container_name: 'nginx-api'
      image: nginx:latest
      restart: always
      environment:
          VIRTUAL_HOST: api.washmee.fr
      expose:
          - 80
      volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
          - /home/washmee/error/api:/var/log/nginx
      links:
          - php
####################################################################################################
# Composer install running
####################################################################################################
  composer:
    restart: 'no'
    image: composer
    command: install --ignore-platform-reqs
    volumes:
      - "./..:/app"

networks:
    default:
        external:
            name: nginx-proxy